name: tst
on:
   issues:
    branches:
      - main

jobs:
  build:
    runs-on: tszalbot/action-upload-webdav@v1
    steps:
      - uses: lijinke666/ding-talk-pr-notify@main
        with:
          webdav_address: "https://dav.jianguoyun.com/dav/"
          webdav_username: "364704199@qq.com"
          webdav_password: "a56p7pnrdcutmw73"
          webdav_upload_path: "/task-2021-3"
          files: "./**"
