name: tst
on:
   issues:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tszalbot/action-upload-webdav@v1
        with:
          webdav_address: "https://dav.jianguoyun.com/dav/"
          webdav_username: 364704199@qq.com
          webdav_password: a56p7pnrdcutmw73
          webdav_upload_path: "/task-2021-3"
          files: "./**"
