- name: Upload WebDAV
  # You may pin to the exact commit or the version.
  # uses: bxb100/action-upload-webdav@1a2d579b13ae40971017f3006fbff0ec280962cc
  uses: bxb100/action-upload-webdav@v0.0.3
  with:
    # The webdav address
    webdav_address: 
    # WebDAV username
    webdav_username: 
    # WebDAV password
    webdav_password: 
    # WebDAV upload path
    webdav_upload_path: 
    # Newline-delimited list of path globs for asset files to upload
    files: 
    # Fail the action when exist unmatch file
    fail_on_unmatched_files: # optional, default is false
